version: '3'
services:
    tgc_db_pg:
        build: 
            context: ./dbs/postgres
            dockerfile: DockerfileDB_PG
        ports:
            - "5432:5432"
    tgc_db_cassandra:
        build: 
          context: ./dbs/cassandra
          dockerfile: DockerfileDB_CAS
        ports:
            - "9042:9042"
              #    db_elasticsearch:
              #        build:
              #    context: ./dbs/elasticsearch
              # dockerfile: DockerfileDB_ES
              #        ulimits:
#          memlock:
#            soft: -1
#            hard: -1
#        environment:
#          - node.name=es01
#          - cluster.name=es-docker-cluster
#          - discovery.type=single-node
#          - bootstrap.memory_lock=true
#          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#        ports:
#            - "9200:9200"
